[API]
TOKEN = "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"
MISTRAL_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-v0.1"
XLSUM_URL = "https://api-inference.huggingface.co/models/csebuetnlp/mT5_multilingual_XLSum"
FLUX_URL = "https://api-inference.huggingface.co/models/black-forest-labs/FLUX.1-schnell"